# Generated by Django 4.1.3 on 2022-12-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0002_registration_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=250)),
                ("department", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("incident_location", models.CharField(max_length=250)),
                ("severity", models.CharField(max_length=250)),
                ("suspected_cause", models.CharField(max_length=250)),
                ("action", models.CharField(max_length=250)),
                ("sub_incident", models.CharField(max_length=250)),
                ("user", models.CharField(max_length=200)),
            ],
        ),
    ]
